#!/usr/bin/env python3
"""Generate a blue-noise threshold mask with Ulichney's void-and-cluster method (1993).

Output: src/halftone/bluenoise64.c, a 64x64 table of thresholds 0..254 (row-major). A pixel is
printed black when its ink value (0..255) exceeds the threshold. Deterministic (fixed seed).

Method: a binary pattern on a torus is relaxed so that its 1s are evenly spread (energy = sum
of Gaussian-weighted neighbours). Ranks are then assigned by repeatedly removing the tightest
cluster (below the initial density) and filling the largest void (above it). Rank order becomes
the threshold order, so every density level from 0 to 100% is a well-spread blue-noise pattern.
"""
import math
import random
import sys

N = 64
SIGMA = 1.5
R = 6
SEED = 20260902


def main(out_path):
    random.seed(SEED)
    kernel = [((dy, dx), math.exp(-(dx * dx + dy * dy) / (2 * SIGMA * SIGMA)))
              for dy in range(-R, R + 1) for dx in range(-R, R + 1)]

    def make_energy(pattern):
        e = [0.0] * (N * N)
        for i, v in enumerate(pattern):
            if v:
                bump(e, i, 1.0)
        return e

    def bump(e, i, sign):
        y, x = divmod(i, N)
        for (dy, dx), w in kernel:
            e[((y + dy) % N) * N + (x + dx) % N] += sign * w

    def tightest_cluster(pattern, e):
        best, bi = -1.0, -1
        for i in range(N * N):
            if pattern[i] and e[i] > best:
                best, bi = e[i], i
        return bi

    def largest_void(pattern, e):
        best, bi = 1e30, -1
        for i in range(N * N):
            if not pattern[i] and e[i] < best:
                best, bi = e[i], i
        return bi

    # initial binary pattern: 10% ones, then relax
    ones = N * N // 10
    pattern = [0] * (N * N)
    for i in random.sample(range(N * N), ones):
        pattern[i] = 1
    energy = make_energy(pattern)
    while True:
        c = tightest_cluster(pattern, energy)
        pattern[c] = 0
        bump(energy, c, -1.0)
        v = largest_void(pattern, energy)
        if v == c:
            pattern[c] = 1
            bump(energy, c, 1.0)
            break
        pattern[v] = 1
        bump(energy, v, 1.0)

    rank = [0] * (N * N)
    # phase 1: remove the tightest clusters from the initial pattern, ranks ones-1 .. 0
    p, e, n = pattern[:], energy[:], ones
    while n > 0:
        c = tightest_cluster(p, e)
        p[c] = 0
        bump(e, c, -1.0)
        n -= 1
        rank[c] = n
    # phase 2 and 3: fill the largest voids, ranks ones .. N*N-1
    p, e, n = pattern[:], energy[:], ones
    while n < N * N:
        v = largest_void(p, e)
        p[v] = 1
        bump(e, v, 1.0)
        rank[v] = n
        n += 1

    thresholds = [r * 255 // (N * N) for r in rank]
    assert max(thresholds) <= 254 and min(thresholds) == 0
    with open(out_path, "w") as f:
        f.write("/* Generated by scripts/gen-bluenoise.py (void-and-cluster, %dx%d, sigma %.1f, seed %d).\n"
                " * Threshold mask: print black when ink > table[y %% %d][x %% %d]. Do not edit. */\n"
                "#include \"m2022/halftone.h\"\n\n"
                "const uint8_t m2022_bluenoise64[%d * %d] = {\n" % (N, N, SIGMA, SEED, N, N, N, N))
        for y in range(N):
            f.write("    " + ", ".join("%3d" % thresholds[y * N + x] for x in range(N)) + ",\n")
        f.write("};\n")
    print("wrote", out_path)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "src/halftone/bluenoise64.c")
